version: '3'

services:
  dns-server:
    build:
      context: ./
      args:
        - http_proxy
        - https_proxy
    ports:
      - "${DNS_PROXY_LOGGER_BIND_IP:-127.0.0.1}:53:53"
      - "${DNS_PROXY_LOGGER_BIND_IP:-127.0.0.1}:53:53/udp"
    dns:
      - ${DNS_PROXY_LOGGER_FORWARD_IP_1}
      - ${DNS_PROXY_LOGGER_FORWARD_IP_2}
    restart: always
